-- AlterTable
ALTER TABLE `Invoice` ADD COLUMN `customerType` VARCHAR(191) NOT NULL DEFAULT 'MURID';
ALTER TABLE `Invoice` ADD COLUMN `customerName` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `Invoice` ADD COLUMN `program` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `Invoice` ADD COLUMN `date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE `Invoice` ADD COLUMN `items` JSON;
ALTER TABLE `Invoice` ADD COLUMN `total` DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE `Invoice` ADD COLUMN `paymentLink` VARCHAR(191);
